### ISSUE TITLE
Crash on server start

### ISSUE THREAD

**Issue by Neubulae** [flori-schwa/VarLightFabric#2]
https://pastebin.com/UfgpfsLR

**Comment by flori-schwa** [comment]
Server and fabric version?

**Comment by Neubulae** [comment]
> Server and fabric version?

Server version 1.15.2, Fabric version could be 0.7.8

**Comment by flori-schwa** [comment]
I'll take a look when I'm back from work.

**Comment by flori-schwa** [comment]
This is sadly a known issue with fabric FabricMC/intermediary#6

**Comment by Neubulae** [comment]
> This is sadly a known issue with fabric [FabricMC/intermediary#6](https://github.com/FabricMC/intermediary/issues/6)

So would you provide a workaround for it? Or the mod is sadly unusable atm...?

**Comment by flori-schwa** [comment]
I will try to get a workaround working

**Comment by Neubulae** [comment]
> I will try to get a workaround working

Ok, thanks for the great work!

**Comment by flori-schwa** [comment]
Fixed in [1.1.1](https://github.com/flori-schwa/VarLightFabric/releases/tag/1.1.1)

**Comment by Neubulae** [comment]
> Fixed in [1.1.1](https://github.com/flori-schwa/VarLightFabric/releases/tag/1.1.1)

I have already downloaded it lol. thx
